fixed:
  dataset: peptides-struct
  log_path: './logs'

  use_wandb: False
  wandb_name: "peptides"
  wandb_prefix: "peptides_normal"

  sample_configs:
    sample_policy: null
    sample_k: null
    ensemble: 0
    include_original_graph: True

  imle_configs: null

  optim: "adam"
  model: gin_normal
  hid_size: 256
  lr: 1.e-3
  lr_decay:
    scheduler: step
    steps: '[ 200, 400 ]'
  early_stop:
    patience: 100
    target: val_metric
  reg: 0.
  num_convlayers: 4
  mlp_layers_intragraph: 3
#  mlp_layers_intergraph: 0
  graph_pooling: mean
#  inter_graph_pooling: null
  dropout: 0.
  bn: True
  residual: True
  batch_size: 64
  min_epochs: 700
  max_epochs: 1000
  data_path: './datasets'
  debug: False
  num_runs: 2
