program: main.py
method: bayes
entity: mls-stuttgart
project: peptides-sweep
name: peptides-sweep
run_cap: 30

metric:
  goal: minimize
  name: val_loss

parameters:
  # read data
  dataset:
    value: peptides-struct
  log_path:
    value: './logs'
  data_path:
    value: './datasets'

  # debugger mode
  num_runs:
    value: 1
  use_wandb:
    value: True
  debug:
    value: False

  # sample configs, shared by random and learnable sampling methods
  sample_configs.sample_policy:
    value: None
  sample_configs.sample_k:
    value: None
  sample_configs.ensemble:
    value: 0
  sample_configs.include_original_graph:
    value: True

  # sampler and its hyperparams
  imle_configs:
    value: None

  model:
    value: pepstruct_gin
  hid_size:
    values:
      - 256
      - 128
  num_convlayers:
    values:
      - 2
      - 3
      - 4
  mlp_layers_intragraph:
    value: 3
  mlp_layers_intergraph:
    value: 0
  inter_graph_pooling:
    value: None

  # downstream training
  lr:
    value: 1.e-3
  lr_decay.scheduler:
    value: step
  lr_decay.steps:
    value: '[ 200, 400 ]'
  optim:
    value: adam
  early_stop.patience:
    value: 100
  early_stop.target:
    value: val_metric
  reg:
    value: 0.
  batch_size:
    value: 64
  min_epochs:
    value: 300
  max_epochs:
    value: 1000
