fixed:
  dataset: qm9
  log_path: './logs'

  use_wandb: False
  wandb_project: "experiment"
  wandb_name: "name"

  sample_configs:
    separate: False
    directed: False
    sample_k: 20   # edge addition
    sample_k2: 5   # edge deletion
    candid_pool: 100
    ensemble: 1
    heuristic: longest_path
    include_original_graph: True

  imle_configs:
    num_train_ensemble: 3
    num_val_ensemble: 3

    model: "edge_selector"
    emb_hid_size: 64
    gnn_layer: 8
    mlp_layer: 4
    batchnorm: True

  task_id: 1
  model: qm9gine
  hid_size: 128
  lr: 1.e-3
  lr_decay:
    decay_rate: 0.5
    mode: 'min'
    patience: 50
  early_stop:
    patience: 150
  reg: 0.
  num_convlayers: 4
  mlp_layers_intragraph: 0
  mlp_layers_intergraph: 2
  graph_pooling: max
  inter_graph_pooling: cat
  dropout: 0.2
  bn: True  # placeholder
  residual: True  # placeholder
  batch_size: 256
  min_epochs: 400
  max_epochs: 1000
  data_path: './datasets'
  debug: False
  num_runs: 1
