fixed:
  dataset: qm9
  log_path: './logs'

  use_wandb: False
  wandb_name: "qm9_normal"

  sample_configs:
    sample_policy: null
    sample_k: null
    ensemble: 0   # config just for plots
    include_original_graph: True   # config just for plots

  imle_configs: null

  # down stream model
  model: gine_normal
  hid_size: 64
  lr: 1.e-3
  optim: adam
  lr_decay: null
  early_stop:
    patience: 100
    target: val_metric
  reg: 0.
  num_convlayers: 8
  mlp_layers_intragraph: 3
#  mlp_layers_intergraph: 0
  graph_pooling: max
#  inter_graph_pooling: null
  dropout: 0.5
  bn: True
  residual: True
  batch_size: 32
  min_epochs: 300
  max_epochs: 1000
  data_path: './datasets'
  debug: False
  num_runs: 3