fixed:
  dataset: zinc
  log_path: './logs'

  use_wandb: True
  wandb_name: "edge_candid"

  sample_configs:
    sample_policy: edge_candid
    in_place: True    # add the edges to the original graphs
    sample_k: 10
    candid_pool: 30
    ensemble: 1
    include_original_graph: True

  imle_configs:
    sampler: simple
    logits_activation: 'None'
    weight_edges: marginals
    marginals_mask: True
    negative_sample: 'full'
    num_train_ensemble: 1
    num_val_ensemble: 1

    model: "edge_selector"
    rwse:
      kernel: 20
      layers: 2
      dim_pe: 32
      raw_norm_type: 'BatchNorm'

    lap:
      max_freqs: 4
      dim_pe: 32
      layers: 2
      raw_norm_type: null

    emb_hid_size: 256
    emb_optim: "adamw"
    emb_scheduler: "cosine"
    num_layer: 4
    dropout: 0.
    embd_lr: 1.e-3
    reg_embd: 0.
    batchnorm: True
    micro_batch_embd: 1

  rwse:
    kernel: 20
    layers: 2
    dim_pe: 16
    raw_norm_type: 'BatchNorm'
  lap:
    max_freqs: 4
    dim_pe: 16
    layers: 2
    raw_norm_type: null

  optim: "adam"
  model: gin_duo
  hid_size: 256
  lr: 1.e-3
  lr_decay:
    scheduler: step
    steps: '[ 400, 600 ]'
  early_stop:
    patience: 100
    target: val_metric
  reg: 0.
  num_convlayers: 4
  mlp_layers_intragraph: 3
  mlp_layers_intergraph: 2
  graph_pooling: mean
  inter_graph_pooling: cat
  dropout: 0.
  bn: True
  residual: True
  batch_size: 128
  min_epochs: 700
  max_epochs: 1000
  data_path: './datasets'
  debug: False
  num_runs: 2
