fixed:
  dataset: alchemy
  log_path: './logs'

  use_wandb: True
  wandb_name: "alchemy_normal"

  sample_configs:
    sample_policy: null
    sample_k: null
    ensemble: 0   # config just for plots
    include_original_graph: True   # config just for plots

  imle_configs: null

  # down stream model
  model: gin_normal
  hid_size: 64
  lr: 1.e-3
  optim: adam
  lr_decay:
    scheduler: step
    steps: '[ 400, 600 ]'
  #  lr_decay:
  #    scheduler: plateau
  #    mode: min
  #    decay_rate: 0.5
  #    patience: 50
  #    target: val_metric
  early_stop:
    patience: 100
    target: val_metric
  reg: 0.
  num_convlayers: 6
  mlp_layers_intragraph: 2
  #  mlp_layers_intergraph: 0
  graph_pooling: set2set
  #  inter_graph_pooling: null
  dropout: 0.
  bn: True
  residual: True
  batch_size: 128
  min_epochs: 700
  max_epochs: 1000
  data_path: './datasets'
  debug: False
  num_runs: 3