fixed:
  dataset: ogbg-molesol
  log_path: './logs'

  sample_configs:
    sample_policy: greedy_neighbors
    subgraph2node_aggr: center
    sample_k: 10
    ensemble: 1
    # for inner model
    inner_layer: 5
    extra_dim: [0, 300]  # data.x || subgraph_emb

  imle_configs: null

  model: ogb_gin
  dropout: 0.5
  hid_size: 300
  lr: 1.e-3
  lr_steps: [ 10000, 99999 ]
  patience: 100
  reg: 0.
  num_convlayers: 0
  batch_size: 32
  min_epochs: 100
  max_epochs: 300
  data_path: './datasets'
  debug: False
  num_runs: 3