fixed:
  dataset: ogbg-molesol
  log_path: './logs'

  sample_configs:
    sample_policy: greedy_neighbors
    subgraph2node_aggr: center
    sample_k: 5
    # for inner model
    inner_layer: 3
    extra_dim: [0, 300]  # data.x || subgraph_emb

  imle_configs: null
