fixed:
  dataset: ogbg-molesol
  log_path: './logs'

  sample_configs:
    sample_policy: khop
    subgraph2node_aggr: mean
    sample_k: 2
    # for inner model
    inner_layer: 5
    extra_dim: [0, 300]  # data.x || subgraph_emb

  imle_configs: null
