common:
  model: arxiv_sage
  dataset: ogbn-arxiv
  dropout: 0.5
  khop: 3
  hid_size: 256
  lr: 1.e-3
  lr_steps: [ 500, 600 ]
  patience: 50
  reg: 0.
  num_convlayers: 3
  batch_size: 128
  min_epochs: 700
  max_epochs: 1000
  data_path: './datasets'
  debug: False
  num_runs: 3