# see https://github.com/tkipf/pygcn/blob/master/pygcn/train.py
common:
  model: planetoid_gin
  dataset: cora
  dropout: 0.5
  khop: 2
  hid_size: 16
  lr: 1.e-2
  lr_steps: [ 10000, 99999 ]
  patience: 20
  reg: 5.e-4
  num_convlayers: 2
  batch_size: 32
  min_epochs: 200
  max_epochs: 300
  data_path: './datasets'
  debug: False
  num_runs: 3
