common:
  model: ogb_gin
  dataset: ogbg-molesol
  dropout: 0.5
  hid_size: 300
  lr: 1.e-3
  lr_steps: [ 10000, 99999 ]
  patience: 100
  reg: 0.
  num_convlayers: 5
  batch_size: 32
  min_epochs: 100
  max_epochs: 300
  data_path: './datasets'
  debug: False
  num_runs: 3
