fixed:
  dataset: ogbg-molesol
  log_path: './logs'

  sample_configs:
    sample_policy: null
    subgraph2node_aggr: null
    sample_k: null
    # for inner model
    inner_layer: 3

  imle_configs: null