fixed:
  dataset: ogbg-molhiv
  log_path: './logs'

  use_wandb: True
  wandb_project: "experiment"
  wandb_name: "name"

  sample_configs:
    separate: False
    directed: False
    sample_k: 10   # edge addition
    sample_k2: 0   # edge deletion
    candid_pool: 512
    ensemble: 1
    heuristic: longest_path
    include_original_graph: True

  imle_configs:
    num_train_ensemble: 5
    num_val_ensemble: 5

    model: "edge_selector"
    rwse:
      kernel: 20
      layers: 2
      dim_pe: 32
      raw_norm_type: 'BatchNorm'
    # lap does not work for molesol

    emb_hid_size: 128
    emb_optim: "adamw"
    emb_scheduler: None
    gnn_layer: 4
    mlp_layer: 4
    dropout: 0.
    embd_lr: 1.e-3
    reg_embd: 0.
    batchnorm: True

  rwse:
    kernel: 20
    layers: 2
    dim_pe: 16
    raw_norm_type: 'BatchNorm'
  # lap does not work for molesol

  optim: "adam"
  model: gine_duo
  hid_size: 128
  lr: 1.e-3
  lr_decay:
    scheduler: 'plateau'
    decay_rate: 0.5
    mode: 'max'
    patience: 20
    target: 'val_metric'
  early_stop:
    patience: 50
    target: val_metric
  reg: 0.
  num_convlayers: 5
  mlp_layers_intragraph: 2
  mlp_layers_intergraph: 2
  graph_pooling: mean
  inter_graph_pooling: cat
  dropout: 0.1
  bn: True
  residual: True
  batch_size: 56
  min_epochs: 50
  max_epochs: 1000
  data_path: './datasets'
  debug: False
  num_runs: 3
