fixed:
  dataset: ogbg-molhiv
  log_path: './logs'

  sample_configs:
    sample_policy: null
    subgraph2node_aggr: null
    sample_k: null
    # for inner model
    inner_layer: 5
    extra_dim: [0, 300]  # data.x || subgraph_emb

  imle_configs: null

  # common settings
  model: ogb_gin
  dropout: 0.5
  hid_size: 300
  lr: 1.e-3
  lr_steps: [ 10000, 99999 ]
  patience: 100
  reg: 0.
  num_convlayers: 0  # outer
  batch_size: 32
  min_epochs: 100
  max_epochs: 100
  data_path: './datasets'
  debug: False
  num_runs: 3