fixed:
  dataset: leafcolor_4
  log_path: './logs'

  use_wandb: False
  wandb_name: "leafcolor_4"

  sample_configs:
    sample_policy: edge_candid
    separate: True
    directed: True
    sample_k: 16
    sample_k2: 32
    ensemble: 1
    candid_pool: 32
    in_place: True
    heuristic: all
    include_original_graph: False

  imle_configs:
    sampler: simple
    logits_activation: 'None'
    weight_edges: marginals
    marginals_mask: True
    num_train_ensemble: 1
    num_val_ensemble: 1

    model: "edge_selector"
    emb_hid_size: 128
    emb_optim: "adamw"
    emb_scheduler: null
    gnn_layer: 4
    mlp_layer: 3
    dropout: 0.
    embd_lr: 1.e-3
    reg_embd: 0.
    batchnorm: True

  model: gin_duo
  hid_size: 32
  lr: 1.e-3
  optim: adam
  lr_decay:
    scheduler: plateau
    decay_rate: 0.5
    patience: 10000
    mode: max
    target: train_metric
  early_stop:
    patience: 20000
    target: train_metric
  reg: 0.
  num_convlayers: 1
  mlp_layers_intragraph: 3
  mlp_layers_intergraph: 1
  graph_pooling: root
  inter_graph_pooling: cat
  dropout: 0.
  bn: False
  residual: False
  batch_size: 1024
  min_epochs: 0
  max_epochs: 50000
  data_path: './datasets'
  debug: False
  num_runs: 3