fixed:
  dataset: leafcolor_4
  log_path: './logs'

  use_wandb: True
  wandb_name: "leafcolor4-16"
  wandb_prefix: "trainens_5_128"

  sample_configs:
    sample_policy: global
    directed: True
    separate: True
    sample_k: 16
    sample_k2: 0
    ensemble: 1
    in_place: False
    include_original_graph: True

  imle_configs:
    sampler: simple
    logits_activation: 'None'
    weight_edges: 'None'
    marginals_mask: True
    num_train_ensemble: 1
    num_val_ensemble: 1
    negative_sample: "full"

    model: "transformer"
    heads: 4   # see GraphGPS https://github.com/rampasek/GraphGPS/blob/main/configs/GPS/zinc-GPS-LapPE%2BRWSE.yaml#L51

    emb_hid_size: 128
    emb_optim: "adam"
    emb_scheduler: "cosine"
    tf_layer: 0
    dropout: 0.
    attn_dropout: 0.
    embd_lr: 1.e-3
    reg_embd: 0.
    layernorm: False
    batchnorm: True
    spectral_norm: True   # spectral normalization
    micro_batch_embd: 1

    auxloss:
      variance: 0.
      degree: 0.
      origin_bias: 0.
  
  model: gin_duo
  hid_size: 128
  lr: 1.e-3
  optim: adam
  lr_decay:
    scheduler: plateau
    decay_rate: 0.5
    patience: 10000
    mode: max
    target: train_metric
  early_stop:
    patience: 20000
    target: train_metric
  reg: 0.
  num_convlayers: 1
  mlp_layers_intragraph: 3
  mlp_layers_intergraph: 1
  graph_pooling: root
  inter_graph_pooling: cat
  dropout: 0.
  bn: False
  residual: False
  batch_size: 1024
  min_epochs: 0
  max_epochs: 50000
  data_path: './datasets'
  debug: False
  num_runs: 3

  plot_graphs:
    batch_id: 0
    plot_every: 100
    n_graphs: 2
    dataset: 'leafcolor'
    plot_folder: './debugs'