fixed:
  dataset: peptides-struct
  log_path: './logs'

  use_wandb: True
  wandb_name: "peptides"
  wandb_prefix: "edge_candid"

  sample_configs:
    sample_policy: edge_candid
    sample_k: 30
    candid_pool: 1024
    ensemble: 1
    include_original_graph: True

  imle_configs:
    sampler: imle
    logits_activation: 'None'
    weight_edges: None
    marginals_mask: True
    num_val_ensemble: 1
    num_train_ensemble: 1
    negative_sample: "full"

    model: "edge_selector"
    rwse:
      kernel: 20
      layers: 2
      dim_pe: 32
      raw_norm_type: 'BatchNorm'

    lap:
      max_freqs: 4
      dim_pe: 32
      layers: 2
      raw_norm_type: null

    emb_hid_size: 256
    emb_optim: "adamw"
    emb_scheduler: "cosine"
    num_layer: 4
    dropout: 0.
    embd_lr: 1.e-3
    reg_embd: 0.
    batchnorm: True
    micro_batch_embd: 1
    noise_scale: 0.3
    beta: 10.

  input_feature: 64
  rwse:
    kernel: 20
    layers: 2
    dim_pe: 16
    raw_norm_type: 'BatchNorm'
  lap:
    max_freqs: 4
    dim_pe: 16
    layers: 2
    raw_norm_type: null

  optim: "adam"
  model: pepstruct_gin_duo
  hid_size: 256
  lr: 1.e-3
  lr_decay:
    scheduler: step
    steps: '[ 400, 600 ]'
  early_stop:
    patience: 100
    target: val_metric
  reg: 0.
  num_convlayers: 4
  mlp_layers_intragraph: 3
  mlp_layers_intergraph: 2
  inter_graph_pooling: 'cat'
  batch_size: 8
  min_epochs: 700
  max_epochs: 1000
  data_path: './datasets'
  debug: False
  num_runs: 2
