fixed:
  dataset: zinc
  log_path: './logs'

  use_wandb: True

  sample_configs:
    sample_policy: global_topk
    sample_k: 20
    ensemble: 1
    include_original_graph: True

  imle_configs:
    sampler: gumbel
    tau: 0.1

    model: "graphormer"
    heads: 4

    attenbias:   # https://github.com/rampasek/GraphGPS/blob/main/configs/Graphormer/zinc-Graphormer.yaml#L24
      num_spatial_types: 20
      num_in_degrees: 64
      num_out_degrees: 64

    emb_hid_size: 64
    tf_layer: 2
    dropout: 0.    # https://github.com/rampasek/GraphGPS/blob/main/configs/Graphormer/zinc-Graphormer.yaml#L41
    attn_dropout: 0.1
    input_dropout: 0.1
    mlp_dropout: 0.1
    embd_lr: 1.e-3
    reg_embd: 0.
    micro_batch_embd: 1

    aux_type: 'batch'   # batch or pair
    auxloss: 0.0

  model: zinc_gin
  hid_size: 256
  lr: 1.e-3
  lr_steps: [ 400, 600 ]
  patience: 100
  reg: 0.
  num_convlayers: 4
  mlp_layers_intragraph: 3
  mlp_layers_intergraph: 0
  batch_size: 128
  min_epochs: 700
  max_epochs: 1000
  data_path: './datasets'
  debug: False
  num_runs: 5
