fixed:
  dataset: zinc
  log_path: './logs'

  use_wandb: True
  wandb_name: "imle_ablate"

  sample_configs:
    sample_policy: global_topk_directed
    sample_k: 20
    ensemble: 4
    include_original_graph: False

  imle_configs:
    sampler: simple

    model: "graphormer"
    heads: 4

    attenbias:   # https://github.com/rampasek/GraphGPS/blob/main/configs/Graphormer/zinc-Graphormer.yaml#L24
      num_spatial_types: 20
      num_in_degrees: 64
      num_out_degrees: 64

    emb_hid_size: 64
    tf_layer: 0
    dropout: 0.    # https://github.com/rampasek/GraphGPS/blob/main/configs/Graphormer/zinc-Graphormer.yaml#L41
    attn_dropout: 0.1
    input_dropout: 0.1
    mlp_dropout: 0.1
    embd_lr: 1.e-3
    reg_embd: 0.
    spectral_norm: True   # spectral normalization
    micro_batch_embd: 1

    auxloss:
      variance: 0.
      degree: 0.
      origin_bias: 0.

  model: zinc_gin
  hid_size: 256
  lr: 1.e-3
  lr_decay:
    scheduler: step
    steps: '[ 400, 600 ]'
  early_stop:
    patience: 100
    target: val_metric
  reg: 0.
  num_convlayers: 4
  mlp_layers_intragraph: 3
  mlp_layers_intergraph: 0
  inter_graph_pooling: null
  batch_size: 128
  min_epochs: 700
  max_epochs: 1000
  data_path: './datasets'
  debug: False
  num_runs: 2

  plot_graphs:
    batch_id: 0
    plot_every: 10
    n_graphs: 4
    plot_folder: './plots_graphormer'
