fixed:
  dataset: zinc
  log_path: './logs'

  sample_configs:
    sample_policy: global_topk
    sample_k: 20
    ensemble: 1
    include_original_graph: True

  imle_configs:
    sampler: simple

    model: "lin_inner"
    heads: 1    # for attention-like inner product
    emb_edge: False
    emb_spd: True
    emb_ppr: False

    emb_hid_size: 64
    gnn_layer: 2
    mlp_layer: 2
    dropout: 0.
    embd_lr: 1.e-3
    reg_embd: 0.
    bn: False
    micro_batch_embd: 1

    aux_type: 'batch'   # batch or pair
    auxloss: 0.0

  model: zinc_gin
  hid_size: 256
  lr: 1.e-3
  lr_steps: [ 400, 600 ]
  patience: 100
  reg: 0.
  num_convlayers: 4
  batch_size: 128
  min_epochs: 700
  max_epochs: 1000
  data_path: './datasets'
  debug: False
  num_runs: 5
