fixed:
  dataset: proteins
  log_path: './logs'

  use_wandb: True
  wandb_project: "experiment"
  wandb_name: "name"


  sample_configs:
    separate: False
    directed: False
    sample_k: 10   # edge addition
    sample_k2: 10   # edge deletion
    candid_pool: 1024
    ensemble: 3
    heuristic: longest_path
    include_original_graph: False

  imle_configs:
    num_train_ensemble: 5
    num_val_ensemble: 5

    model: "edge_selector"

    emb_hid_size: 32
    emb_optim: "adamw"
    emb_scheduler: None
    gnn_layer: 8
    mlp_layer: 2
    dropout: 0.
    embd_lr: 1.e-3
    reg_embd: 0.
    batchnorm: True


  optim: "adam"
  model: gine_duo
  hid_size: 32
  lr: 1.e-3
  lr_decay:
    scheduler: 'plateau'
    decay_rate: 0.5
    mode: 'max'
    patience: 30
    target: 'val_metric_ensemble'
  early_stop:
    patience: 50
    target: val_metric_ensemble

  reg: 0.
  num_convlayers: 4
  mlp_layers_intragraph: 3
  mlp_layers_intergraph: 1
  graph_pooling: mean
  inter_graph_pooling: cat
  dropout: 0.1
  bn: True
  residual: True
  batch_size: 128
  min_epochs: 200
  max_epochs: 1000
  data_path: './datasets'
  debug: False
  num_runs: 3

