fixed:
  dataset: zinc
  log_path: './logs'

  sample_configs:
    sample_policy: graph_topk
    sample_k: 5
    ensemble: 2
    include_original_graph: True

  imle_configs: null

  model: zinc_gin
  hid_size: 256
  lr: 1.e-3
  lr_steps: [ 400, 600 ]
  patience: 100
  reg: 0.
  num_convlayers: 4
  batch_size: 128
  min_epochs: 700
  max_epochs: 1000
  data_path: './datasets'
  debug: False
  num_runs: 5
