fixed:
  dataset: ogbg-molesol
  log_path: './logs'

  sample_configs:
    sample_policy: soft_all
    subgraph2node_aggr: add
    sample_k: null
    ensemble: 1
    # for inner model
    inner_layer: 3
    extra_dim: [300, 300]  # data.x || subgraph_emb

  imle_configs:
    model: 'fwl'
    emb_edge: True
    emb_spd: True

    emb_hid_size: 64
    gnn_layer: 3
    mlp_layer: 3
    dropout: 0.
    embd_lr: 1.e-3
    reg_embd: 0.
    bn: True  # MUST NEEDED!!!!
    micro_batch_embd: 1
    noise_scale: null
    beta: null

  model: ogb_gin
  dropout: 0.5
  hid_size: 300
  lr: 1.e-3
  lr_steps: [ 200, ]
  patience: 100
  reg: 0.
  num_convlayers: 5
  batch_size: 32
  min_epochs: 300
  max_epochs: 400
  data_path: './datasets'
  debug: False
  num_runs: 5