fixed:
  dataset: peptides-struct
  log_path: './logs'

  use_wandb: True
  wandb_name: "best_edge_candid_seq_peptides_struct"

  sample_configs:
    sample_policy: edge_candid
    per_layer: False
    separate: False
    directed: True
    in_place: True
    sample_k: 10   # edge addition
    sample_k2: 100   # edge deletion
    candid_pool: 500
    ensemble: 1
    heuristic: longest_path
    include_original_graph: False

  imle_configs:
    sampler: simple
    noise_scale: 0.3
    beta: 10.
    logits_activation: null
    weight_edges: None
    marginals_mask: True
    negative_sample: 'full'
    num_train_ensemble: 1
    num_val_ensemble: 5

    model: "edge_selector"
    rwse:
      kernel: 20
      layers: 2
      dim_pe: 32
      raw_norm_type: 'BatchNorm'

    lap:
      max_freqs: 4
      dim_pe: 32
      layers: 2
      raw_norm_type: null

    emb_hid_size: 256
    emb_optim: "adamw"
    emb_scheduler: None
    gnn_layer: 16
    mlp_layer: 2
    dropout: 0.
    embd_lr: 1.e-3
    reg_embd: 0.
    batchnorm: True

  rwse:
    kernel: 20
    layers: 2
    dim_pe: 16
    raw_norm_type: 'BatchNorm'
  lap:
    max_freqs: 4
    dim_pe: 16
    layers: 2
    raw_norm_type: null

  optim: "adam"
  model: gine_duo
  hid_size: 256
  lr: 1.e-3
  lr_decay:
    scheduler: 'plateau'
    decay_rate: 0.5
    mode: 'max'
    patience: 50
    target: 'val_metric'
  early_stop:
    patience: 200
    target: val_metric
  reg: 0.
  num_convlayers: 4
  mlp_layers_intragraph: 3
  mlp_layers_intergraph: 2
  graph_pooling: mean
  inter_graph_pooling: cat
  dropout: 0.
  bn: True
  residual: True
  batch_size: 128
  min_epochs: 250
  max_epochs: 1000
  data_path: './datasets'
  debug: False
  num_runs: 3

  # plot_graphs:
  #   batch_id: 0
  #   plot_every: 100
  #   n_graphs: 5
#    plot_folder: './plots'