fixed:
  dataset: tree_4
  log_path: './logs'

  use_wandb: False
  wandb_name: "imle_ablate"

  sample_configs:
    sample_policy: null
    sample_k: null
    ensemble: 0   # config just for plots
    include_original_graph: True   # config just for plots

  imle_configs: null

  model: tree_gin
  hid_size: 32
  lr: 1.e-3
  optim: adam
  lr_steps: '[ 400, 600 ]'
  patience: 100
  reg: 0.
  num_convlayers: 5   # depth + 1
  inter_graph_pooling: null
  batch_size: 128
  min_epochs: 700
  max_epochs: 1000
  data_path: './datasets'
  debug: False
  num_runs: 3