fixed:
  dataset: zinc
  log_path: './logs'

  use_wandb: False
  wandb_project: "experiment"
  wandb_name: "name"

  sample_configs:
    separate: False
    directed: False
    sample_k: 80   # edge addition
    sample_k2: 20   # edge deletion
    candid_pool: 100
    ensemble: 5
    heuristic: longest_path
    include_original_graph: True

  imle_configs:
    num_train_ensemble: 1
    num_val_ensemble: 5

    model: "edge_selector"

    emb_hid_size: 64
    gnn_layer: 8
    mlp_layer: 4
    batchnorm: True

#  rwse:
#    kernel: 20
#    layers: 2
#    dim_pe: 16
#    raw_norm_type: 'BatchNorm'
  lap:
    max_freqs: 4
    dim_pe: 16
    layers: 2
    raw_norm_type: null

  hid_size: 256
  lr: 1.e-3
  lr_decay:
    decay_rate: 0.5
    mode: 'min'
    patience: 150
  early_stop:
    patience: 200
  reg: 0.
  num_convlayers: 4
  mlp_layers_intragraph: 3
  mlp_layers_intergraph: 2
  graph_pooling: mean
  inter_graph_pooling: cat
  dropout: 0.
  bn: True
  residual: True
  batch_size: 128
  min_epochs: 400
  max_epochs: 1000
  data_path: './datasets'
  debug: True
  num_runs: 3