fixed:
  dataset: zinc
  log_path: './logs'

  use_wandb: True
  wandb_name: "zinc_normal"
  wandb_project: "new_debug"

  sample_configs:
    separate: False
    directed: False
    sample_k: 80   # edge addition
    sample_k2: 20   # edge deletion
    candid_pool: 100
    ensemble: 5
    heuristic: longest_path
    include_original_graph: True

  rwse:
    kernel: 20
    layers: 2
    dim_pe: 16
    raw_norm_type: 'BatchNorm'

  lap:
    max_freqs: 4
    dim_pe: 16
    layers: 2
    raw_norm_type: null

  imle_configs: null

  # down stream model
  model: gine_normal
  hid_size: 256
  lr: 1.e-3
  optim: adam
  lr_decay:
    scheduler: plateau
    mode: min
    decay_rate: 0.5
    patience: 150
    target: val_metric
  early_stop:
    patience: 200
    target: val_metric
  reg: 0.
  num_convlayers: 4
  mlp_layers_intragraph: 3
#  mlp_layers_intergraph: 0
  graph_pooling: mean
#  inter_graph_pooling: null
  dropout: 0.
  bn: True
  residual: True
  batch_size: 128
  min_epochs: 700
  max_epochs: 1000
  data_path: './datasets'
  debug: False
  num_runs: 3