fixed:
  dataset: zinc
  log_path: './logs'

  use_wandb: True

  sample_configs:
    sample_policy: global_topk
    sample_k: 20
    ensemble: 1
    directed: False
    include_original_graph: True

  imle_configs: null

  model: zinc_gin
  hid_size: 256
  lr: 1.e-3
  lr_steps: [ 400, 600 ]
  patience: 100
  reg: 0.
  num_convlayers: 4
  mlp_layers_intragraph: 3
  mlp_layers_intergraph: 0
  batch_size: 128
  min_epochs: 700
  max_epochs: 1000
  data_path: './datasets'
  debug: False
  num_runs: 3
