program: main.py
method: bayes
entity: mls-stuttgart
project: sweep_cornell_normal
name: sweep_cornell_normal
run_cap: 30

metric:
  goal: maximize
  name: val_metric

parameters:
  # read data
  dataset:
    value: hetero_cornell
  log_path:
    value: './logs'
  data_path:
    value: './datasets'

  # debugger mode
  num_runs:
    value: 1
  use_wandb:
    value: True
  debug:
    value: False

  # sample configs, shared by random and learnable sampling methods
  sample_configs.sample_policy:
    value: None
  sample_configs.in_place:
    value: None
  sample_configs.sample_k:
    value: None
  sample_configs.ensemble:
    value: 0
  sample_configs.include_original_graph:
    value: True

  # sampler and its hyperparams
  imle_configs:
    value: None

  # downstream model
  model:
    value: gin_normal
  hid_size:
    values:
      - 64
      - 128
      - 192
      - 256
    distribution: categorical
  num_convlayers:
    values:
      - 2
      - 3
      - 4
    distribution: categorical
  mlp_layers_intragraph:
    values:
      - 1
      - 2
      - 3
    distribution: categorical
  mlp_layers_intergraph:
    values:
      - 1
      - 2
      - 3
    distribution: categorical
  graph_pooling:
    value: transductive
  dropout:
    value: 0.
  bn:
    value: True
  residual:
    value: True
  inter_graph_pooling:
    value: cat

  lr:
    value: 1.e-3
  lr_decay.scheduler:
    value: plateau
  lr_decay.mode:
    value: max
  lr_decay.decay_rate:
    value: 0.5
  lr_decay.patience:
    value: 50
  lr_decay.target:
    value: val_metric
  optim:
    value: adam
  early_stop.patience:
    value: 100
  early_stop.target:
    value: val_metric
  reg:
    value: 0.
  batch_size:
    value: 128
  min_epochs:
    value: 300
  max_epochs:
    value: 1000
