fixed:
  dataset: zinc
  log_path: './logs'

  use_wandb: True
  wandb_name: "imle_ablate"

  sample_configs:
    sample_policy: add_del
    in_place: True
    sample_k: 80
    sample_k2: 20
    ensemble: 1
    include_original_graph: True

  imle_configs: null

  rwse:
    kernel: 20
    layers: 2
    dim_pe: 16
    raw_norm_type: 'BatchNorm'
  lap:
    max_freqs: 4
    dim_pe: 16
    layers: 2
    raw_norm_type: null

  model: gine_duo
  hid_size: 256
  lr: 1.e-3
  optim: adam
  lr_decay:
    scheduler: step
    steps: '[ 400, 600 ]'
  early_stop:
    patience: 100
    target: val_metric
  reg: 0.
  num_convlayers: 4
  mlp_layers_intragraph: 3
  mlp_layers_intergraph: 2
  graph_pooling: mean
  inter_graph_pooling: cat
  dropout: 0.
  bn: True
  residual: True
  batch_size: 128
  min_epochs: 700
  max_epochs: 1000
  data_path: './datasets'
  debug: False
  num_runs: 3
