fixed:
  dataset: zinc
  log_path: './logs'

  sample_configs:
    sample_policy: graph_topk
    subgraph2node_aggr: mean
    sample_k: 10
    ensemble: 1
    # for inner model
    inner_layer: 2
    extra_dim: [256, 256]  # data.x || subgraph_emb

  imle_configs:
    model: "lin_inner"
    emb_edge: False
    emb_spd: True
    emb_ppr: True

    emb_hid_size: 64
    gnn_layer: 2
    mlp_layer: 2
    dropout: 0.
    embd_lr: 1.e-3
    reg_embd: 0.
    bn: True  # MUST NEEDED!!!!
    micro_batch_embd: 1
    noise_scale: 0.3
    beta: 10.

    auxloss: 1.

  model: zinc_gin
  hid_size: 256
  lr: 1.e-3
  lr_steps: [ 400, 600 ]
  patience: 100
  reg: 0.
  num_convlayers: 4
  batch_size: 128
  min_epochs: 700
  max_epochs: 1000
  data_path: './datasets'
  debug: False
  num_runs: 5
