fixed:
  dataset: cora
  log_path: './logs'

  sample_configs:
    sample_policy: topk
    subgraph2node_aggr: add
    sample_k: 0.8
    ensemble: 1

  imle_configs:
    model: planetoid_gcn
    emb_hid_size: 16
    emb_num_layer: 2
    dropout: 0.
    embd_lr: 1.e-3
    reg_embd: 0.
    micro_batch_embd: 1
    noise_scale: 1.
    beta: 10.
