fixed:
  dataset: tree_4
  log_path: './logs'

  use_wandb: False
  wandb_name: "tree4"

  sample_configs:
    sample_policy: global
    separate: True
    directed: True
    sample_k: 10
    sample_k2: 0
    ensemble: 1
    in_place: False
    include_original_graph: True

  imle_configs:
    sampler: simple
    logits_activation: 'None'
    weight_edges: marginals
    marginals_mask: True
    negative_sample: 'full'
    num_train_ensemble: 1
    num_val_ensemble: 1

    model: "transformer"
    heads: 4   # see GraphGPS https://github.com/rampasek/GraphGPS/blob/main/configs/GPS/zinc-GPS-LapPE%2BRWSE.yaml#L51

    emb_hid_size: 32
    emb_optim: "adamw"
    emb_scheduler: "cosine"
    tf_layer: 2
    dropout: 0.
    attn_dropout: 0.5
    embd_lr: 1.e-3
    reg_embd: 0.
    layernorm: False
    batchnorm: True
    spectral_norm: True   # spectral normalization
    micro_batch_embd: 1

    auxloss:
      variance: 0.
      degree: 0.
      origin_bias: 0.01
  
  model: gin_duo
  hid_size: 32
  lr: 1.e-3
  optim: adam
  lr_decay:
    scheduler: plateau
    decay_rate: 0.5
    patience: 10000
    mode: max
    target: train_metric
  early_stop:
    patience: 20000
    target: train_metric
  reg: 0.
  num_convlayers: 1
  mlp_layers_intragraph: 3
  mlp_layers_intergraph: 1
  graph_pooling: root
  inter_graph_pooling: cat
  dropout: 0.
  bn: False
  residual: False
  batch_size: 1024
  min_epochs: 0
  max_epochs: 50000
  data_path: './datasets'
  debug: False
  num_runs: 3

  plot_graphs:
    batch_id: 0
    plot_every: 1000
    n_graphs: 4