fixed:
  dataset: zinc
  log_path: './logs'

  sample_configs:
    sample_policy: greedy_neighbors
    subgraph2node_aggr: center
    sample_k: 15
    ensemble: 1
    # for inner model
    inner_layer: 1
    extra_dim: [0, 256]  # data.x || subgraph_emb

  imle_configs: null