fixed:
  dataset: csl
  log_path: './logs'

  use_wandb: False
  wandb_project: "experiment"
  wandb_name: "name"

  sample_configs:
    separate: False
    directed: False
    sample_k: 1   # edge addition
    sample_k2: 0   # edge deletion
    candid_pool: 1
    ensemble: 3
    heuristic: longest_path
    include_original_graph: False

  imle_configs:
    num_train_ensemble: 3
    num_val_ensemble: 10

    model: "edge_selector"

    emb_hid_size: 32
    emb_optim: "adamw"
    emb_scheduler: None
    gnn_layer: 64
    mlp_layer: 3
    dropout: 0.
    embd_lr: 1.e-3
    reg_embd: 0.
    batchnorm: True

  optim: "adam"
  model: gin_duo
  hid_size: 128
  lr: 1.e-3
  lr_decay:
    scheduler: 'plateau'
    decay_rate: 0.9
    mode: 'max'
    patience: 20
    target: 'val_metric_ensemble'
  early_stop:
    patience: 50
    target: val_metric_ensemble

  reg: 0.
  num_convlayers: 12
  mlp_layers_intragraph: 2
  mlp_layers_intergraph: 2
  graph_pooling: mean
  inter_graph_pooling: cat
  dropout: 0.
  bn: True
  residual: True
  batch_size: 32
  min_epochs: 100
  max_epochs: 1000
  data_path: './datasets'
  debug: False
  num_runs: 3