fixed:
  dataset: edge_wt_region_boundary
  log_path: './logs'

  use_wandb: False
  wandb_name: "voc"
  wandb_prefix: "normal"

  sample_configs:
    sample_policy: null
    sample_k: null
    ensemble: 0
    include_original_graph: True

  imle_configs: null

  lap:
    max_freqs: 10
    dim_pe: 16
    layers: 2
    raw_norm_type: null

  optim: "adam"
  model: voc_gin
  hid_size: 166
  lr: 1.e-3
  lr_decay:
    scheduler: step
    steps: '[ 300, 500 ]'
  early_stop:
    patience: 100
    target: val_metric
  reg: 0.
  num_convlayers: 8
  mlp_layers_intragraph: 3
  mlp_layers_intergraph: 0
  inter_graph_pooling: null
  batch_size: 64
  min_epochs: 500
  max_epochs: 1000
  data_path: './datasets'
  debug: False
  num_runs: 2
